export const projects = [
    { id: 7, title: "دقمة", client: "DQMA", category: "هوية بصرية", image: "/doma/doma-1.webp", year: "2023", size: "large", description: 'هوية بصرية متكاملة لعلامة تجارية سعودية، تعكس تراثها وقيمها بلمسة عصرية. شمل المشروع تصميم الشعار، واختيار لوحة الألوان، وإرشادات الطباعة لضمان حضور متسق ومؤثر للعلامة التجارية.', images: ['/doma/doma-1.webp','/doma/doma-2.webp','/doma/doma-3.webp','/doma/doma-4.webp','/doma/doma-5.webp','/doma/doma-6.webp','/doma/doma-7.webp','/doma/doma-8.webp','/doma/doma-9.webp',]},
    { id: 8, title: "شادن", client: "شادن", category: "علامة تجارية", image: "/shaden/shaden-1.webp", year: "2023", size: "medium", description: 'شادن هي علامة تجارية قمنا بتصميمها لشركة ملابس وفساتين محتشمة. أردنا أن ننقل إحساسًا كلاسيكيًا وهادئًا مع الحفاظ على لمسة من الفخامة، وهو ما عكسناه في الألوان. الشعار عبارة عن كلمة مكتوبة بخط النسخ لكلمة "شادن" باللغة العربية، والتي تعني "الغزال".', images: ['/shaden/shaden-1.webp','/shaden/shaden-2.webp','/shaden/shaden-3.webp','/shaden/shaden-4.webp','/shaden/shaden-5.webp','/shaden/shaden-6.webp','/shaden/shaden-7.webp','/shaden/shaden-8.webp','/shaden/shaden-9.webp',]},
    { id: 9, title: "مامافنتشرز", client: "مامافنتشرز", category: "هوية العلامة التجارية", image: "/mamaventures/mamaventures-1.webp", year: "2023", size: "medium", description: 'تصميم هوية العلامة التجارية للعميل @mamaventures_. ترث هذه العلامة التجارية طابع الرعاية النهارية للأطفال، والألوان الزاهية، والمرئيات البسيطة لتكون أقرب إلى جمهورها المستهدف. والنتيجة هي علامة تجارية مرحة وسهلة المنال تلقى صدى لدى كل من الأطفال والآباء.', images: ['/mamaventures/mamaventures-1.webp','/mamaventures/mamaventures-2.webp','/mamaventures/mamaventures-3.webp','/mamaventures/mamaventures-8.webp','/mamaventures/mamaventures-9.webp','/mamaventures/mamaventures-10.webp','/mamaventures/mamaventures-11.webp',]},
    { id: 1, title: "شركة تقنية ناشئة", client: "تك إنوفيشن", category: "هوية بصرية متكاملة", image: "/images/gallery-1.webp", year: "2024", size: "large", description: 'تصميم هوية بصرية متكاملة لشركة تقنية ناشئة، مع التركيز على الابتكار والحداثة.', images: ['/images/gallery-1.webp']},
    { id: 2, title: "مطعم فاخر", client: "مذاق الأصالة", category: "شعار وهوية", image: "/images/gallery-2.webp", year: "2024", size: "medium", description: 'تصميم شعار وهوية بصرية لمطعم فاخر، يجمع بين الأصالة والعصرية.', images: ['/images/gallery-2.webp']},
    { id: 3, title: "متجر أزياء", client: "أناقة عصرية", category: "سوشيال ميديا", image: "/images/gallery-3.webp", year: "2024", size: "medium", description: 'إدارة وتصميم محتوى لوسائل التواصل الاجتماعي لمتجر أزياء عصري.', images: ['/images/gallery-3.webp']},
    { id: 4, title: "عيادة طبية", client: "مركز الشفاء الطبي", category: "هوية بصرية", image: "/images/gallery-4.webp", year: "2023", size: "small", description: 'تصميم هوية بصرية لعيادة طبية، تعكس الثقة والاحترافية.', images: ['/images/gallery-4.webp']},
    { id: 5, title: "شركة استشارات", client: "رؤى للاستشارات", category: "هوية بصرية متكاملة", image: "/images/gallery-5.webp", year: "2023", size: "small", description: 'هوية بصرية متكاملة لشركة استشارات، تركز على النمو والنجاح.', images: ['/images/gallery-5.webp']},
    { id: 6, title: "كافيه متخصص", client: "قهوة الحرفيين", category: "شعار وتطبيقات", image: "/images/gallery-6.webp", year: "2023", size: "large", description: 'تصميم شعار وتطبيقات متنوعة لكافيه متخصص بالقهوة.', images: ['/images/gallery-6.webp']}
];